const crypto = require('crypto');
const COOKIE = 'campus_dashboard_session';
const OPERATOR_COOKIE = 'campus_operator_session';
const MAX_AGE = 60 * 60 * 8;
function sign(value) { return crypto.createHmac('sha256', process.env.DASHBOARD_SESSION_SECRET || '').update(value).digest('base64url'); }
function cookieOptions(maxAge = MAX_AGE) { return `${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`; }
function sessionCookie() { const payload = Buffer.from(JSON.stringify({ exp: Math.floor(Date.now() / 1000) + MAX_AGE })).toString('base64url'); return `${COOKIE}=${payload}.${sign(payload)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${MAX_AGE}`; }
function hasSession(req) { const match = (req.headers.cookie || '').match(new RegExp(`${COOKIE}=([^;]+)`)); if (!match) return false; const [payload, signature] = match[1].split('.'); if (!payload || !signature || !process.env.DASHBOARD_SESSION_SECRET) return false; const expected = sign(payload); if (signature.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return false; try { return JSON.parse(Buffer.from(payload, 'base64url').toString()).exp > Math.floor(Date.now() / 1000); } catch { return false; } }
function requireSession(req, res) { if (hasSession(req)) return true; res.statusCode = 401; res.setHeader('Cache-Control', 'private, no-store'); res.end(JSON.stringify({ error: 'unauthorized' })); return false; }
function signWith(value, secret) { return crypto.createHmac('sha256', secret).update(value).digest('base64url'); }
function operatorSessionCookie() { const operatorId = process.env.HANDOFF_OPERATOR_ID; const role = process.env.HANDOFF_OPERATOR_ROLE; const secret = process.env.HANDOFF_OPERATOR_SESSION_SECRET; if (!operatorId || !['OWNER', 'OPERATOR'].includes(role) || !secret) return null; const payload = Buffer.from(JSON.stringify({ exp: Math.floor(Date.now() / 1000) + MAX_AGE, operator_id: operatorId, role })).toString('base64url'); return `${OPERATOR_COOKIE}=${payload}.${signWith(payload, secret)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${MAX_AGE}`; }
function operatorFromSession(req) { const match = (req.headers.cookie || '').match(new RegExp(`${OPERATOR_COOKIE}=([^;]+)`)); const secret = process.env.HANDOFF_OPERATOR_SESSION_SECRET; if (!match || !secret) return null; const [payload, signature] = match[1].split('.'); if (!payload || !signature) return null; const expected = signWith(payload, secret); if (signature.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; try { const value = JSON.parse(Buffer.from(payload, 'base64url').toString()); if (value.exp <= Math.floor(Date.now() / 1000) || !value.operator_id || !['OWNER', 'OPERATOR'].includes(value.role)) return null; return { operator_id: value.operator_id, role: value.role }; } catch { return null; } }
function requireOperator(req, res) { const operator = operatorFromSession(req); if (operator) return operator; res.statusCode = 401; res.setHeader('Cache-Control', 'private, no-store'); res.end(JSON.stringify({ error: 'operator_unauthorized' })); return null; }
module.exports = { cookieOptions, hasSession, requireSession, sessionCookie, operatorSessionCookie, operatorFromSession, requireOperator };
