const assert=require('node:assert/strict');
const fs=require('node:fs');
const core=require('../core/omega-concierge-core');
const runtime=fs.readFileSync('assets/omega-concierge.js','utf8');
const index=fs.readFileSync('index.html','utf8');
assert(index.indexOf('core/omega-concierge-core.js')<index.indexOf('handoff/omega-handoff-context.js'));
assert(index.indexOf('handoff/omega-handoff-context.js')<index.indexOf('assets/omega-concierge.js'));
assert.equal(typeof core.respondToMessage,'function');
assert(runtime.includes('core.respondToMessage(state,text'));
assert(runtime.includes('window.omegaHandoffContext.buildHandoffContext'));
assert(runtime.includes('if(state.handoff_active&&state.handoff_context)return state.handoff_context'));
assert(runtime.includes("state.handoff_id=state.handoff_id||('handoff-'+state.conversation_id+'-'+Date.now())"));
const coreSource=fs.readFileSync('core/omega-concierge-core.js','utf8');
assert(coreSource.includes("q.indexOf('cuánto cuesta')"));
assert(coreSource.includes("q.indexOf('caro')"));
assert(coreSource.includes("q.indexOf('inscrib')"));
console.log('Gate 05 05.1C runtime integration contract: PASS');
